Install Helm

diff --git a/Jenkinsfile.deploy b/Jenkinsfile.deploy
--- a/Jenkinsfile.deploy
+++ b/Jenkinsfile.deploy
@@ -9,6 +9,20 @@ pipeline {
     }
 
     stages {
+
+        stage('Install Helm') {
+            steps {
+                sh """
+                    if ! command -v helm &> /dev/null; then
+                        echo "Helm not found. Installing..."
+                        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+                    else
+                        echo "Helm is already installed."
+                    fi
+                """
+            }
+        }
+
         stage('Check and Create Namespace') {
             steps {
                 script {
